name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: ğŸš€ Pipeline
    timeout-minutes: 15

    steps:
      - name: âœ‹ğŸ¼ Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v2

      - name: ğŸ“¥ Install Dependencies
        run: npm install --no-audit --no-fund --omit=optional

      - name: ğŸ’… Lint
        run: npm run lint

      - name: ğŸ‘·ğŸ»â€â™€ï¸ Build
        run: npm run build

      - name: âœ… Unit tests
        run: npm run test
